version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - blogmicro-networks

  user-service:
    container_name: user-service
    image: user-service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
      - api-gateway
      - service-registry
      - config-server
      - rabbitmq
    networks:
      - blogmicro-networks
    restart: on-failure

  blogpost-service:
    container_name: blogpost-service
    image: blogpost-service
    build:
      context: ./blogpost_service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/post_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
      - api-gateway
      - service-registry
      - config-server
      - rabbitmq
    networks:
      - blogmicro-networks
    restart: on-failure

  category-service:
    container_name: category-service
    image: category-service
    build:
      context: ./category-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/category_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8084:8084"
    depends_on:
      - mysqldb
      - api-gateway
      - service-registry
      - config-server
      - rabbitmq
    networks:
      - blogmicro-networks
    restart: on-failure

  comment-service:
    container_name: comment-service
    image: comment-service
    build:
      context: ./comment-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/comment_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8083:8083"
    depends_on:
      - mysqldb
      - api-gateway
      - service-registry
      - config-server
      - rabbitmq
    networks:
      - blogmicro-networks
    restart: on-failure

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - service-registry
    networks:
      - blogmicro-networks
    restart: on-failure

  config-server:
    container_name: config-server
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - service-registry
    networks:
      - blogmicro-networks
    restart: on-failure

  service-registry:
    container_name: service-registry
    image: service-registry
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - blogmicro-networks

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.0
    ports:
      - "5672:5672"
    networks:
      - blogmicro-networks
networks:
  blogmicro-networks:

volumes:
  db_data: